---
displayName: Java EAP Microprofile
description: Java stack with EAP 7.3, OpenJDK 11 and Maven 3.5
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Microprofile"]
icon: /images/type-jboss.svg
globalMemoryLimit: 2674Mi
