---
displayName: Java EAP Maven
description: RHEL 8 Java stack with EAP 7.2.7, OpenJDK 1.8 and Maven 3.5.4
tags: ["Java", "OpenJDK", "Maven", "EAP"]
icon: /images/type-jboss.svg
globalMemoryLimit: 2674Mi
