---
displayName: Java EAP Maven
description: Java stack with EAP XP 1.0, OpenJDK 8 and Maven 3.5
tags: ["RHEL7", "Java", "OpenJDK", "Maven", "EAP"]
icon: /images/type-jboss.svg
globalMemoryLimit: 3186Mi
