---
displayName: Java Vert.x
description: Java stack with OpenJDK 8, Maven 3.5.4 and Vert.x demo application
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Vertx"]
icon: /images/type-vertx.svg
globalMemoryLimit: 2674Mi
