---
displayName: NodeJS MongoDB
description: NodeJS stack with NPM 6.13.4, NodeJS 10.19.0 and MongoDB 3.4
tags: ["NodeJS", "Express", "MongoDB", "NPM", "UBI8"]
icon: /images/type-node.svg
globalMemoryLimit: 1686Mi
