---
displayName: ".NET"
description: .NET 3.1 stack with .NET Core SDK and Runtime
tags: [".NET", "C#"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-dotnet.svg?sanitize=true
globalMemoryLimit: 2198Mi
