---
displayName: Red Hat Fuse
description: Red Hat Fuse stack with EAP 7.2.7, OpenJDK 1.8 and Maven 3.5.4
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Red Hat Fuse"]
icon: /images/type-fuse.svg
globalMemoryLimit: 2816Mi
